#!/usr/bin/env node

const program = require('commander');
const { version } = require('../package.json')
const cwd = process.cwd()
const split = name => name.split('/')
const creatProject = require('./createProject')
const creatPage = require('./createPage')
const creatComponent = require('./createComponent')
program
  .version(version, '-v, --version')
  .option('-i, --init [name]', '创建项目', '')
  .option('-c, --component <n>', '创建class组件', split)
  .option('-f, --function <n>', '创建函数式组件', split)
  .option('-p, --page <n>', '创建容器页面', split)
  .parse(process.argv)

if (program.init) {
  creatProject(program.init)
} else if (program.component) {
  creatComponent(cwd, program.component)
} else if (program.function) {
  creatComponent(cwd, program.function, true)
} else if (program.page) {
  creatPage(cwd, program.page)
} else {
  console.log('请输入指定的参数，或者执行crcto -h查询操作规则')
}